# Generated by Django 3.0.1 on 2019-12-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0004_auto_20191225_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(default='film_app/no_cover.jpg', upload_to='film_app/'),
        ),
    ]
